# These are supported funding model platforms

github: [pserwylo]

# Note that the display name for the organisation is "Baby Apps" now, but the actually account in both liberapay and github is just "babydots".
liberapay: BabyDots
